version: "3.8"
services:
  postgres:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  # other services...
