version: '3.8'
services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    volumes:
      - .:/app