server.port=8083
spring.application.name=service-lis

spring.datasource.url=${DB_URL:jdbc:h2:mem:lisdb;DB_CLOSE_DELAY=-1}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=false
spring.h2.console.enabled=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

lis.rabbitmq.exchange=lis.exchange
lis.rabbitmq.routing-key=lis.lab-order.created
lis.rabbitmq.queue=lis.lab-order-created.queue
lis.rabbitmq.result-routing-key=lis.lab-result.ready
lis.rabbitmq.result-queue=lis.lab-result-ready.queue
