server:
  port: 8080

spring:
  application:
    name: cloud-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem
  cloud:
    gateway:
      routes:
        - id: service-his
          uri: ${HIS_URI:http://localhost:8081}
          predicates:
            - Path=/api/patients/**
        - id: service-emr
          uri: ${EMR_URI:http://localhost:8082}
          predicates:
            - Path=/api/encounters/**
        - id: service-lis
          uri: ${LIS_URI:http://localhost:8083}
          predicates:
            - Path=/api/lab-orders/**
        - id: service-emr-ws
          uri: ${EMR_WS_URI:ws://localhost:8082}
          predicates:
            - Path=/ws/**
      default-filters:
        - PreserveHostHeader

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
