server:
  port: 8083

spring:
  application:
    name: tenant-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/erp_kernel}
    username: ${DB_USER:erp}
    password: ${DB_PASS:erp}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: kernel_tenant
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    schemas: kernel_tenant
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
